blog/2015-02-27-fusetooling-news.adoc
fixed some typos and did rewording
=> corrections for the fuse tooling blog post

_config/products.yml
=> JBTIS-412 - update release notes for JBDSIS 8.0.0.GA

_config/products.yml
Needed separate -name for the EA zip files.
=> JBTIS-441 - correct jbtis/ jbdsis zip file xml fragments

documentation/howto/index.adoc
@xcoulon, implemented a minor change after discussing it with Max for the index. Could you have a look and then merge this please?
=> TOOLSDOC-620-b: Changed index header order as discussed in TOOLSDOC-620

documentation/howto/generate_html5_web_app.adoc, documentation/howto/import_fh_app.adoc
Second try at commit request. @xcoulon could you have a look at this and confirm it only has two adoc files included please?
=> TOOLSDOC-649: Added introductions to feedhenry and html5 articles

documentation/whatsnew/arquillian/arquillian-news-4.3.0.CR1.adoc, documentation/whatsnew/batch/batch-news-4.3.0.CR1.adoc, documentation/whatsnew/central/central-news-2.0.0.CR1.adoc, documentation/whatsnew/docker/docker-news-1.1.0.adoc, documentation/whatsnew/examples/examples-news-4.3.0.CR1.adoc, documentation/whatsnew/hibernate/hibernate-news-4.3.0.CR1.adoc, documentation/whatsnew/javascript/javascript-news-4.3.0.CR1.adoc, documentation/whatsnew/livereload/livereload-news-1.3.0.CR1.adoc, documentation/whatsnew/maven/maven-news-4.3.0.CR1.adoc, documentation/whatsnew/openshift/openshift-news-3.0.0.CR1.adoc, documentation/whatsnew/server/server-news-4.3.0.CR1.adoc
Minor edits to N&N content for CR1
=> TOOLSDOC-681: Minor edits to N&N content for CR1

_config/products.yml, _ext/downloads.rb, _ext/products_helper.rb, _ext/whatsnew.rb, _layouts/whatsnew_aggregated.html.haml
Part 1 of the resolution:
- include the description for 4.3.0.Final in products.yml
- fix the product build label to "Coming soon" since no release date is set.
=> JBIDE-20851 - Skip Final NN aggregation page if "include-previous: false"

_ext/asciidoctor/related_jira.rb, _ext/downloads.rb, _ext/products_helper.rb, _layouts/downloads_per_eclipse_stream_summary.html.haml, _layouts/whatsnew.html.haml
Fix broken build on Travis because the "Nightly build" download
page was not created.
=> JBIDE-20851 - Skip Final NN aggregation page if "include-previous: false

documentation/howto/openshift_importapp.adoc
Minor addition and some formatting changes. @xcoulon could you please have a look and merge if OK?
=> TOOLSDOC-307a: Updated article with minor changes

blog/we-are-hiring-qe.adoc
Multiple job openings to fill - let's list them on the blog
=> Added blog post to highlight January 2016 QE job openings

documentation/whatsnew/docker/docker-news-1.2.0.Mars2.adoc, documentation/whatsnew/forge/forge-news-4.3.1.Beta1.adoc, documentation/whatsnew/forge/forge-news-4.3.1.Beta2.adoc, documentation/whatsnew/freemarker/freemarker-news-4.3.1.Beta1.adoc, documentation/whatsnew/general/general-4.3.1.Beta1.adoc, documentation/whatsnew/jst/jst-news-4.3.1.Beta1.adoc, documentation/whatsnew/openshift/openshift-news-3.1.0.Beta1.adoc, documentation/whatsnew/openshift/openshift-news-3.1.0.Beta2.adoc
Added editorial suggestions for N&N content for Beta1 and Beta2.
@xcoulon or @mmalina, can you review and merge or provide feedback please.
=> TOOLSDOC-706: Edits suggested for N&N content for Beta1 and Beta2

blog/eclipse_neon_webinar_series.adoc
@xcoulon I have uploaded presentation to SlideShare. Could  you please merge ?
=> [blog] Changing JSDT 2.0 presentation link to SlideShare

documentation/whatsnew/freemarker/freemarker-news-4.4.1.AM2.adoc
=> JBIDE 22835 Freemarker New and Noteworthy for 4.4.1.AM2

_config/products.yml
=> release 4.4.1.AM2

_config/products.yml, blog/integration-stack-4.3.1.Final.adoc
@xcoulon - please consider and push - thkx!
=> JBTIS 4.3.1.Final/ JBDSIS 9.0.1.GA

blog/am3-for-neon.adoc
=> Blog for JBoss Tools 4.4.1.AM3

documentation/whatsnew/freemarker/freemarker-news-4.4.1.AM2.adoc, documentation/whatsnew/freemarker/freemarker-news-4.4.1.AM3.adoc, documentation/whatsnew/freemarker/freemarker-news-4.4.1.Final.adoc
While the issue was about writing the N&N for 4.4.1.Final, I have noticed that the AM2 and AM3 N&N missies most of the changes. I hope it's not a problem that I have fixed them retrospectively. Also note that I didn't check the output... hopefully my syntax was right.
=> JBIDE-23111: Freemarker New and Noteworthy updates for 4.4.1.AM2, AM3 and Final

readme.adoc
=> [JBIDE-23163] - Docker settings for secure Linux to be documented

blog/10.1.0.ga-for-neon.adoc
=> Blog for JBossTools 4.4.1.Final and DeveloperStudio 10.1.0.GA

_config/products.yml
add 4.4.2.AM2 to tools.jboss.org
=> add 4.4.2.AM2 to tools.jboss.org

blog/4.4.2.am1.neon.adoc
=> Blog for JBossTools 4.4.2.AM1

blog/am1.4.4.2.neon.adoc, documentation/whatsnew/openshift/openshift-news-3.3.1.AM1.adoc
=> [JBIDE-23246] - OpenShift New and Noteworthy for 4.4.2.AM1

_config/products.yml, blog/integration-stack-4.3.2.Final.adoc
@xcoulon - please consider and push at your convenience
=> JBTIS-4.3.2.Final updates

_config/products.yml
=> add  to tools.jboss.org

blog/am2.4.4.2.neon.adoc
=> Blog for JBossTools 4.4.2.AM2

documentation/whatsnew/openshift/openshift-news-3.3.1.AM3.adoc
=> [JBIDE-23448] - OpenShift New and Noteworthy for 4.4.2.AM3

_config/products.yml
add 4.4.2.AM3 to tools.jboss.org
=> add 4.4.2.AM3 to tools.jboss.org

blog/am3.4.4.2.neon.adoc
=> Blog for JBossTools 4.4.2.AM3

documentation/whatsnew/openshift/openshift-news-3.3.1.AM1.adoc, documentation/whatsnew/openshift/openshift-news-3.3.1.AM2.adoc
- Hide items in 4.4.2.AMx what's new
=> [JBIDE-23547] - OpenShift New and Noteworthy for 4.4.2.Final

blog/10.2.0.ga-for-neon.1.adoc
=> Blog for JBossTools 4.4.2.Final and DeveloperStudio 10.2.0.GA

blog/am1.4.4.3.neon.1.adoc
=> Blog for JBossTools 4.4.3.AM1

_config/products.yml
add 4.4.3.AM1 to tools.jboss.org
=> add 4.4.3.AM1 to tools.jboss.org

documentation/whatsnew/index.html.haml
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
=> JBIDE-23635 - Show newest first on tools.jboss.org/downloads/

_config/products.yml
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
=> JBIDE-23779 - Archive old JBoss Tools versions on the website

_config/products.yml
Signed-off-by: Mat Booth <mat.booth@redhat.com>
=> add 4.4.3.AM2 to tools.jboss.org

_config/products.yml, blog/integration-stack-4.4.1.Final.adoc
Update products yaml and create a blog for JBTIS-4.4.1.Final - DevstudioIS 10.1.0.GA
@xcoulon - please consider and push at your convenience - thkx!
=> JBTIS-4.4.1.Final - DevstudioIS 10.1.0.GA

blog/10.3.0.ga-for-neon.2.adoc
=> Blog for JBossTools 4.4.3.Final and DeveloperStudio 10.3.0.GA

_config/products.yml
Signed-off-by: Mat Booth <mat.booth@redhat.com>
=> add 4.4.3.Final and 10.3.0.GA to tools.jboss.org

_config/products.yml
add 4.4.4.AM1 to tools.jboss.org
=> add 4.4.4.AM1 to tools.jboss.org

_config/products.yml
@jeffmaury - could you push this PR at your convenience?  thkx!
=> JBTIS-4.4.2.Final, DevstudioIS 10.2.0.GA

_config/products.yml
add 4.4.4.AM3 to tools.jboss.org
=> add 4.4.4.AM3 to tools.jboss.org

_config/products.yml, blog/integration-stack-4.4.3.Final.adoc
@xcoulon @jeffmaury - Please consider and push at your convenience - thkx!
=> JBTIS-4.4.3.Final

_data/team/mhusnain.adoc, blog/2017-05-31-devstudio-survey.adoc
Created new blog post for devstudio docs survey. @xcoulon can you review please?
=> New blog post for devstudio survey

_config/products.yml
add 4.5.0.AM1 to tools.jboss.org
=> add 4.5.0.AM1 to tools.jboss.org

_ext/products_helper.rb, _ext/whatsnew_helper.rb, _layouts/whatsnew_aggregated.html.haml, dockerrun.sh
show all .Final and .GA releases in the left nav 
Signed-off-by: nickboldt <nboldt@redhat.com>
=> show all .Final and .GA releases in the left nav

documentation/whatsnew/general/general-4.5.0.Final.adoc
=> JBIDE-24706 - Add Seam component deprecated

documentation/whatsnew/hibernate/hibernate-news-4.5.0.Final.adoc
=> [JBIDE-24708] - Hibernate New and Noteworthy for 4.5.0.Final

_config/products.yml, blog/integration-stack-4.5.0.Final.adoc
Committed with -s this time.
JBTIS-4.5.0.Final/ DevstudioIS 11.0.0.GA
=> Jbtis 4.5.0.final

blog/integration-stack-4.5.0.Final.adoc
Signed-off-by: Paul Leacu <pleacu@redhat.com>
=> JBTIS-4.5.0.Final-2 - tweek

documentation/whatsnew/cdi/cdi-news-4.5.1.AM2.adoc
=> [JBIDE-24909] - CDI New and Noteworthy for 4.5.1.AM2

_config/products.yml
add 4.5.1.AM2 to tools.jboss.org
=> add 4.5.1.AM2 to tools.jboss.org

blog/4.5.1.am2-for-oxygen.1.adoc
=> Blog for JBossTools 4.5.1.AM2

documentation/howto/cdk_howto.adoc
Signed-off-by: Supriya Bharadwaj <sbharadw@redhat.com>
=> RHDEVDOCS-541: Updated the howto for latest changes

blog/4.5.1.am3-for-oxygen.1.adoc
=> Blog for JBossTools 4.5.1.AM3

documentation/whatsnew/openshift/openshift-news-3.4.1.AM3.adoc, documentation/whatsnew/openshift/openshift-news-3.4.1.Final.adoc
=> [JBIDE-25241] - OpenShift New and Noteworthy for 4.5.1.Final

blog/11.1.0.ga-for-oxygen.1A.adoc
=> Blog for JBossTools 4.5.1.Final and DeveloperStudio 11.1.0.GA

_config/products.yml
Signed-off-by: Paul Leacu <pleacu@redhat.com>
Local testing looks good.
=> JBTIS-4.5.1.Beta1b/ DevstudioIS 11.1.0.Beta1b

documentation/whatsnew/openshift/openshift-news-3.4.2.AM1.adoc
=> [JBIDE-25334] - OpenShift New and Noteworthy for 4.5.2.AM1

blog/4.5.2.am1-for-oxygen.1a.adoc
=> Blog for JBossTools 4.5.2.AM1

blog/4.5.2.am2-for-oxygen.1a.adoc
=> Blog for JBossTools 4.5.2.AM2

Gemfile.lock
=> Updated RedCloth dependency

documentation/whatsnew/fusetools/fusetools-news-10.2.0.Final.adoc
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> JBIDE-25525 - fixed typos and removed 404 link

documentation/whatsnew/forge/forge-news-4.5.2.Final.adoc
Provides the N&N requested in JBIDE-25524
Signed-off-by: George Gastaldi <gegastaldi@gmail.com>
=> JBIDE-25518 #comment Create N&N for Forge 4.5.2.Final #close

documentation/whatsnew/openshift/openshift-news-3.4.2.Final.adoc
=> [JBIDE-25530] - OpenShift New and Noteworthy for 4.5.2.Final

blog/rsync-windows-env.adoc
=> Add Windows rsync article

blog/4.5.3.am1-for-oxygen.2.adoc
=> Blog for JBoss Tools 4.5.3.AM1

_config/products.yml, blog/integration-stack-4.5.2.Final.adoc
Signed-off-by: Paul Leacu <pleacu@redhat.com>
DevstudioIS 11.2.0.GA - JBTIS 4.5.2.Final
=> JBTIS 4.5.2.Funbal/ DevstudioIS 11.2.0.GA

documentation/whatsnew/aerogear/aerogear-news-4.5.3.AM2.adoc, documentation/whatsnew/arquillian/arquillian-news-4.5.3.AM2.adoc, documentation/whatsnew/browsersim/browsersim-news-4.5.3.AM2.adoc, documentation/whatsnew/freemarker/freemarker-news-4.5.3.AM2.adoc, documentation/whatsnew/livereload/livereload-news-4.5.3.AM2.adoc
=> [JBIDE-25722] - Central New and Noteworthy for 4.5.3.AM2

documentation/whatsnew/general/general-4.5.3.AM2.adoc
=> [JBIDE-25718] - Base New and Noteworthy for 4.5.3.AM2

blog/4.5.3.am2-for-oxygen.2.adoc
=> Blog for JBoss Tools 4.5.3.AM2

blog/4.5.3.am3-for-oxygen.3.adoc
=> Blog for JBoss Tools 4.5.3.AM3

documentation/whatsnew/openshift/openshift-news-3.4.3.Final.adoc
=> [JBIDE-25852] - OpenShift New and Noteworthy for 4.5.3.Final

blog/11.3.0.ga-for-oxygen.3a.adoc
=> Blog for JBossTools 4.5.3.Final and DeveloperStudio 11.3.0.GA

_config/products.yml
Signed-off-by:...
mark more builds archived
Signed-off-by: nickboldt <nboldt@redhat.com>
=> mark more builds archived

documentation/whatsnew/forge/forge-news-4.6.0.AM1.adoc
Signed-off-by: George Gastaldi <gegastaldi@gmail.com>
=> JBIDE-25928 #comment Create N&N for Forge 4.6.0.AM1 #close

documentation/whatsnew/general/general-4.6.0.AM1.adoc
=> [JBIDE-25928] - Create New and Noteworthy for 4.6.0.AM1

blog/4.6.0.am1-for-photon.0.m6.adoc
=> Blog for JBoss Tools 4.6.0.AM1

documentation/whatsnew/openshift/openshift-news-3.4.4.AM2.adoc
=> [JBIDE-26012] - OpenShift New and Noteworthy for 4.6.0.AM2

blog/4.6.0.am2-for-photon.0.m7.adoc
=> Blog for JBoss Tools 4.6.0.AM2

documentation/whatsnew/fusetools/fusetools-news-11.0.0.AM3.adoc
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> fixed typo in fuse 11 AM3 doc

documentation/whatsnew/webservices/webservices-news-2.0.100.AM3.adoc
=> [JBIDE-26048] - Webservices New and Noteworthy for 4.6.0.AM3

blog/4.6.0.am3-for-photon.0.rc3.adoc
=> Blog for 4.6.0.AM3

documentation/whatsnew/maven/maven-news-4.6.0.Final.adoc
=> [JBIDE-26111] - Maven New and Noteworthy for 4.6.0.Final

documentation/whatsnew/server/server-news-4.6.0.Final.adoc
=> [JBIDE-26113] - Server New and Noteworthy for 4.6.0.Final

blog/rhamt_4.1.0.Final_release.adoc
Signed-off-by: John Steele <johnsteele@redhat.com>
=> WINDUP-2109 - Blog for RHAMT 4.1.0.Final - fix typo

features/openshift.adoc
=> Fix typo in OpenShift features page (fixes #841)

documentation/whatsnew/hibernate/hibernate-news-4.9.0.AM1.adoc
=> [JBIDE-26210] - Hibernate New and Noteworthy for 4.9.0.AM1

_config/products.yml, blog/integration-stack-4.6.0.Final.adoc
Signed-off-by: Paul Leacu <pleacu@redhat.com>
=> JBTIS-4.6.0.Final

documentation/whatsnew/fusetools/fusetools-news-11.1.0.AM2.adoc
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> JBIDE-26244 - N&N Fuse Tooling 11.1.0.AM2 - wsdl 2 rest upgrade

blog/4.9.0.am2.adoc
=> Blog for 4.9.0.AM2 - Fix title

documentation/whatsnew/fusetools/fusetools-news-11.1.0.AM2.adoc
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> FUSETOOLS-3073 - fix bullet points in N&N Fuse Tooling 11.1.0.AM2

documentation/whatsnew/forge/forge-news-4.9.0.AM3.adoc
=> [JBIDE-26267] - Forge New and Noteworthy for 4.9.0.AM3

documentation/whatsnew/server/server-news-4.9.0.AM3.adoc
=> [JBIDE-26271] - Server New and Noteworthy for 4.9.0.AM3

blog/4.9.0.am2.adoc
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> FUSETOOLS-3073 - fix bullet points in 4.9.0AM2 blog post announcement

_config/products.yml
Change-Id:...
add 4.9.0.AM3 to tools.jboss.org
Change-Id: Ibde19cce6c1474009ad21bf866c7a8f4342b0a26
Signed-off-by: nickboldt <nboldt@redhat.com>
=> add 4.9.0.AM3 to tools.jboss.org

blog/4.9.0.am3.adoc
=> Blog for 4.9.0.AM3

blog/4.9.0.am3.adoc, documentation/whatsnew/fusetools/fusetools-news-11.1.0.AM3.adoc
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> JBIDE-26268 - regression note in Fuse Tooling N&N and blog announcement

documentation/whatsnew/hibernate/hibernate-news-4.9.0.Final.adoc
=> [JBIDE-26344] - Hibernate New and Noteworthy for 4.9.0.Final

documentation/whatsnew/fusetools/fusetools-news-11.1.0.AM1.adoc, documentation/whatsnew/fusetools/fusetools-news-11.1.0.AM2.adoc, documentation/whatsnew/fusetools/fusetools-news-11.1.0.AM3.adoc, documentation/whatsnew/fusetools/fusetools-news-11.1.0.Final.adoc
based on https://github.com/jbosstools/jbosstools-website/pull/859
(but cannot do the modification directly on the branch as i'm not a maintainer of this repository)
=>  JBIDE-26348 - added final N&N for Fuse Tooling 11.0 

blog/12.9.0.ga-for-2018-09.adoc
=> Blog for JBossTools 4.9.0.Final and DeveloperStudio 12.9.0.GA

_layouts/project.html.haml
=> Activate DPAL

_layouts/project.html.haml
=> Activate DPAL (2)

Dockerfile, Gemfile.lock
=> Fix Docker build

_config/products.yml
=> add 4.11.0.AM1 to tools.jboss.org

documentation/whatsnew/index.html.haml
=> Use semantic versioning when comparing versions

blog/ij-openshift-connector.adoc
=> Reviewing of IntellIJ OpenShift Connector

blog/ij-openshift-connector.adoc
=> Put video first in the IntelliJ OpenShift Connector blog

documentation/whatsnew/general/general-4.11.0.Final.adoc
=> JBIDE-26595: Base N&N for 4.11.0.Final

documentation/whatsnew/server/server-news-4.11.0.Final.adoc
=> JBIDE-26594: Server N&N for 4.11.0.Final

documentation/whatsnew/maven/maven-news-4.11.0.Final.adoc
=> JBIDE-26592: Maven N&N for 4.11.0.Final

documentation/whatsnew/hibernate/hibernate-news-4.11.0.Final.adoc
=> JBIDE-26587: Hibernate N&N for 4.11.0.Final

blog/12.11.0.ga.adoc
=> Fix 4.11.0.Final / 12.11.0.GA blog

_config/products.yml
=> Add 4.11.0.Final / 12.11.0.GA to tools.jboss.org

blog/quarkus.adoc
=> Add Quarkus article

_config/products.yml, blog/integration-stack-4.11.0.Final.adoc
Signed-off-by: pleacu <pleacu@redhat.com>
=> JBTIS-4.11.0.Final, CodeReady Studio 12.11.0.GA

_config/products.yml, blog/4.12.0.am1.adoc, documentation/whatsnew/server/server-news-4.12.0.AM1.adoc
=> add 4.12.0.AM1 to tools.jboss.org

documentation/howto/cdk_howto.adoc, documentation/howto/index.adoc, documentation/howto/openshift3_getting_started.adoc, documentation/howto/os3_deployimage.adoc, documentation/howto/os3_remote.adoc, documentation/howto/os3_startusing.adoc, documentation/whatsnew/openshift/openshift-news-3.7.0.Final.adoc, features/central.adoc, features/openshift.adoc
=> Add OCP4 support + replaced OpenShift 3 occurences with OpenShift

_config/products.yml
=> Add 4.12.0.Final / 12.12.0.GA to tools.jboss.org

_config/products.yml
=> Fix syntax typo in products.yml

_config/products.yml
=> Fix bad 12.12.0.GA TP URL

_config/products.yml
=> Add 2019-09 stream

_config/products.yml
=> Archive old versions

_config/products.yml
=> add 4.13.0.Final and 12.13.0.GA to tools.jboss.org

project.properties
=> Migrating issues.jboss.org --> issues.redhat.com

blog/12.14.0.ga.adoc, documentation/whatsnew/quarkus/quarkus-news-4.14.0.AM1.adoc, documentation/whatsnew/quarkus/quarkus-news-4.14.0.Final.adoc
=> Fix typos in 12.14.0.GA related files

_config/products.yml
=> add 4.15.0.Final and 12.15.0.GA to tools.jboss.org

_config/products.yml
=> fixed typos in final repos url

_config/products.yml
=> add 4.16.0.AM1 to tools.jboss.org

_config/products.yml
=> add 4.16.0.Final and 12.16.0.GA to tools.jboss.org

blog/12.16.0.ga.adoc, documentation/whatsnew/hibernate/hibernate-news-4.16.0.AM1.adoc
=> JBIDE-27355: Blog for 4.16.0.Final / 12.16.0.GA

blog/4.17.0.am1.adoc, documentation/whatsnew/hibernate/hibernate-news-4.17.0.AM1.adoc, documentation/whatsnew/quarkus/quarkus-news-4.17.0.AM1.adoc
=> Add N&N, blog for 4.17.0.AM1

blog/12.17.0.ga.adoc
=> Blog for 4.17.0.Final / 12.17.0.GA

_config/products.yml
=> add 4.18.0.Final / 12.18.0.GA to tools.jboss.org

.github/workflows/deploy.yml, .github/workflows/pull-request.yml, .github/workflows/surge.yml, Rakefile
=> Add Surge deployment for pull requests

_config/products.yml
=> add 4.19.0.AM1 to tools.jboss.org

_config/products.yml
=> add 4.19.0.Final / 12.19.0.GA to tools.jboss.org

_config/products.yml
=> add 4.19.1.AM1 to tools.jboss.org

blog/12.19.1.ga.adoc, documentation/whatsnew/hibernate/hibernate-news-4.19.1.Final.adoc, documentation/whatsnew/server/server-news-4.19.1.Final.adoc
=> Blog for 4.19.1.Final / 12.19.1.GA

_config/products.yml
=> add 4.19.1.Final / 12.19.1.GA to tools.jboss.org

_config/products.yml
=> add 4.21.0.AM1 to tools.jboss.org

_config/products.yml
=> add 4.21.0.Final / 12.21.0.GA to tools.jboss.org

_config/products.yml, blog/12.21.1.ga.adoc
=> Add 12.21.1.GA to tools.jboss.org

index.html.haml
=> Add Quarkus and OpenShift features to the home page

_config/products.yml, blog/12.21.2.ga.adoc
=> Add 12.21.2.GA to tools.jboss.org

.github/workflows/deploy.yml, .github/workflows/pull-request.yml, Rakefile, readme.adoc, survivalguide.adoc
=> master -> main

blog/12.21.3.ga.adoc, documentation/whatsnew/general/general-4.21.3.Final.adoc, documentation/whatsnew/hibernate/hibernate-news-4.21.3.Final.adoc
=> N&N, Blog for 4.21.3.Final / 12.21.3.GA

_config/products.yml
=> Add 4.21.3.Final/12.21.3.GA to tools.jboss.org

blog/4.23.0.am1.adoc, documentation/whatsnew/hibernate/hibernate-news-4.23.0.AM1.adoc
=> N&N, Blog for 4.23.0.AM1

_config/products.yml
=> add 4.23.0.AM1 to tools.jboss.org

Rakefile
=> JBIDE-28425: Fix rsync for website

_config/products.yml
=> add 4.23.0.Final to tools.jboss.org

_config/products.yml
=> add 4.24.0.AM1 to tools.jboss.org

Rakefile
=> Skip deploy for main branch

.github/workflows/deploy.yml
=> Update ubuntu image in deploy workflow

blog/2022-11-09-component-lifetime-policy.adoc
=> Blog about component lifetime policy

_config/products.yml, _data/team/sbouchet.adoc, blog/4.26.0.am1.adoc
=> add 4.26.0.AM1 to tools.jboss.org

_config/products.yml, blog/4.26.0.final.adoc, documentation/whatsnew/general/general-4.26.0.Final.adoc, documentation/whatsnew/hibernate/hibernate-news-4.26.0.Final.adoc, documentation/whatsnew/openshift/openshift-news-3.21.0.Final.adoc
=> Add 4.26.0.Final to tools.jboss.org
